version: 0.2

env:
  variables:
    ACCOUNT_ID: 557690580165
    REGION: us-west-2
    REPO_NAME: expimage
    IMAGE_TAG: new2
    IMAGE_URI: 557690580165.dkr.ecr.us-west-2.amazonaws.com/expimage:latest
    SONAR_HOST_URL: http://44.204.71.196

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven, Docker, and Trivy...
      - yum install -y maven docker
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building JAR inside app-tier...
      - mvn clean package -DskipTests
      - echo Running SonarQube Analysis...
      - mvn clean verify sonar:sonar \
          -Dsonar.projectKey=project2 \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=sqp_44cab9241ba0cf7f14a9265c33e7c72db83d27eb
      - echo Building Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo Scanning Docker image with Trivy...
      - trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_URI || echo "Trivy scan found vulnerabilities"
      - echo Pushing image to Amazon ECR...
      - docker push $IMAGE_URI
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" deployment.yaml > k8s-out/deployment.yaml
      - cp service.yaml k8s-out/service.yaml
      - echo Done preparing artifacts.

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
