version: 0.2

env:
  variables:
    ACCOUNT_ID: 557690580165
    REGION: us-east-2
    REPO_NAME: expimg-ohio
    IMAGE_TAG: latest
    IMAGE_URI: 557690580165.dkr.ecr.us-east-2.amazonaws.com/expimg-ohio:latest
    SONAR_HOST_URL: http://44.204.71.196
    SONAR_PROJECT_KEY: project2
    SONAR_LOGIN: sqp_44cab9241ba0cf7f14a9265c33e7c72db83d27eb

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and Docker...
      - yum install -y maven docker

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building JAR inside app-tier...
      - mvn clean package -DskipTests
      - echo Running SonarQube Analysis...
      - mvn clean verify -DskipTests sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
      - echo Building Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo Pushing image to Amazon ECR...
      - docker push $IMAGE_URI
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" deployment.yaml > k8s-out/deployment.yaml
      - cp service.yaml k8s-out/service.yaml
      - echo Done preparing artifacts.

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
